/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.me.cc;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int Lista=0x7f05000a;
        public static final int changes=0x7f050011;
        public static final int datosconex=0x7f05000b;
        public static final int host=0x7f050001;
        public static final int image1=0x7f050010;
        public static final int infoconex=0x7f050009;
        public static final int notifi=0x7f05000c;
        public static final int probar=0x7f050007;
        public static final int puertoh=0x7f050004;
        public static final int servidor=0x7f05000d;
        public static final int volver=0x7f050008;
        public static final int widget0=0x7f050000;
        public static final int widget28=0x7f050002;
        public static final int widget29=0x7f050003;
        public static final int widget31=0x7f050005;
        public static final int widget32=0x7f050006;
        public static final int widget34=0x7f05000e;
        public static final int widget37=0x7f05000f;
    }
    public static final class layout {
        public static final int conexion=0x7f030000;
        public static final int main=0x7f030001;
        public static final int view3=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
